"""Add profile_picture field

Revision ID: 423abd10d3cf
Revises: ead2feb61c9c
Create Date: 2025-08-19 22:09:20.125257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423abd10d3cf'
down_revision = 'ead2feb61c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
