"""Add reset_code and reset_code_expiry to users

Revision ID: 53432d5e6004
Revises: a1383fff87a9
Create Date: 2025-09-03 01:52:20.224580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53432d5e6004'
down_revision = 'a1383fff87a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expiry')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
